void makehtml(const char *rootfile="mysubsys.root")
{
  //gROOT->ProcessLine(".T");
  gROOT->ProcessLine(".L htmlfuncs.C");
  loadall();
  OnlMonClient *cl = OnlMonClient::instance();
  OnlMonDraw *acc = new ACCMonDraw();
  cl->registerDrawer(acc);
  OnlMonDraw *bbclvl1 = new BbcLvl1MonDraw();
  cl->registerDrawer(bbclvl1);
  OnlMonDraw *bbc = new BbcMonDraw();
  cl->registerDrawer(bbc);
  OnlMonDraw *daq = DaqMonDraw::instance();
  cl->registerDrawer(daq);
  registerDaq();
  OnlMonDraw *dch = new DchMonDraw();
  cl->registerDrawer(dch);
  OnlMonDraw *emc = new EMCalMonDraw();
  cl->registerDrawer(emc);
  OnlMonDraw *ert = new ERTMaskMonDraw();
  cl->registerDrawer(ert);
  OnlMonDraw *ertlvl1 = new ErtLvl1MonDraw();
  cl->registerDrawer(ertlvl1);
//   OnlMonDraw *fcal = new FcalMonDraw();
//   cl->registerDrawer(fcal);
  OnlMonDraw *fvtx = new FvtxMonDraw();
  cl->registerDrawer(fvtx);
  OnlMonDraw *gl1 = new Gl1MonDraw();
  cl->registerDrawer(gl1);
  // OnlMonDraw *locpol = new LocalPolMonDraw();
  // cl->registerDrawer(locpol);
  OnlMonDraw *mcr = new McrMonDraw();
  cl->registerDrawer(mcr);
  OnlMonDraw *mpc = new MpcMonDraw();
  cl->registerDrawer(mpc);
  OnlMonDraw *mpcex = new MpcExMonDraw();
  cl->registerDrawer(mpcex);
  OnlMonDraw *mui = new muiMonDraw();
  cl->registerDrawer(mui);
  OnlMonDraw *muidlvl1 = new MuidLvl1MonDraw();
  cl->registerDrawer(muidlvl1);
  OnlMonDraw *mutr = new MutrMonDraw();
  cl->registerDrawer(mutr);
  // OnlMonDraw *mutrg = new MutrgMonDraw();
  // cl->registerDrawer(mutrg);
  // OnlMonDraw *mutriglvl1mon = new MutrigLvl1MonDraw();
  // cl->registerDrawer(mutriglvl1mon);
  OnlMonDraw *pad = new PadMonDraw();
  cl->registerDrawer(pad);
  OnlMonDraw *pbgl = new PbGlUMonDraw();
  cl->registerDrawer(pbgl);
  OnlMonDraw *pktsize = new PktSizeMonDraw();
  cl->registerDrawer(pktsize);
//   OnlMonDraw *recomon = new RecoMonDraw();
//   cl->registerDrawer(recomon);
  OnlMonDraw *rich = new RICHMonDraw();
  cl->registerDrawer(rich);
  // OnlMonDraw *rpcmon = new RpcMonDraw();
  // cl->registerDrawer(rpcmon);
  // OnlMonDraw *rpctime = new RpcTimetesterDraw();
  // cl->registerDrawer(rpctime);
  // OnlMonDraw *spin = new SpinMonDraw();
  // cl->registerDrawer(spin);
  // OnlMonDraw *spin2 = new Spin2MonDraw();
  // cl->registerDrawer(spin2);
  OnlMonDraw* svxpixel = new SvxPixelMonDraw();
  cl->registerDrawer(svxpixel);
  OnlMonDraw *svxstrip = new SvxStripMonDraw();
  cl->registerDrawer(svxstrip);
  OnlMonDraw *svxvertex = new SvxVertexDraw();
  cl->registerDrawer(svxvertex);
  OnlMonDraw *tof = new TOFMonDraw();
  cl->registerDrawer(tof);
  OnlMonDraw *tofw = new TOFWMonDraw();
  cl->registerDrawer(tofw);
  OnlMonDraw *zdc = new ZdcMonDraw();
  cl->registerDrawer(zdc);
  OnlMonDraw *zdclvl1 = new ZdcLvl1MonDraw();
  cl->registerDrawer(zdclvl1);
  cl->ReadHistogramsFromFile(rootfile);
  cl->Verbosity(1);
  cl->MakeHtml();
  delete cl;
  gSystem->Exit(0);
}
