#ifndef __DAQHISTOBINDEFS_H__
#define __DAQHISTOBINDEFS_H__

#define DAQTOTALEVENTBIN 1
#define DAQACCEVENTBIN 2
#define DAQCORRUPTEVENTBIN 3
#define DAQMISSINGPACKETEVENTBIN 4
#define DAQBADFRAMESTATUSBIN 5
#define DAQBADABORTGAP 6
#define DAQNOMULTIBUFFER 7
#define DAQNUMBINS 7

#endif
