#ifndef DAQVTXPMONDEFS_H__
#define DAQVTXPMONDEFS_H__

#define SPIROEVTCNTBIN 1
#define SPIRO_ALOSSLOCKBIN 2
#define SPIRO_B_LOSSLOCKBIN 3
#define SPIRO_ASIZEERRORBIN 4
#define SPIRO_B_SIZEERRORBIN 5
#define SPIROPARITYBIN 6
#define SPIROEVTNOBIN 7
#define SPIROCLK03BIN 8
#define SPIROCLK47BIN 9
#define VTXPLASTBIN (SPIROCLK47BIN)


#endif
